author: Noah Gao # 作者
description: Noah's blog
keyword: 博客, 前端, Web
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 Resume: /resume/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: noahziheng
gitment_repo: noahziheng.github.io
gitment_oauth_id: a9a8b8ae317ae422c1eb
gitment_oauth_secret: 017b8d86dc6ee4c9a95b16d37ac432a141541eec

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: f4eb406be058265cf6064b36b379393d

about: 
  banner: /images/banner.jpg
  avatar: https://avatars1.githubusercontent.com/u/2758317?s=460&v=4
  description: God helps those who help themselves.
  # Links
  weibo_username: ziheng1719
  twitter_username: noahziheng
  github_username: noahziheng
  zhihu_username: noah-gao
  douban_username: 